name: Deploy site
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vue3-upgrade-test
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version:  20.x

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "ctubbesing" && git config user.email "connortubbesing@gmail.com"
          npm run gh-pages-deploy